---
- name: setup user1 on host
  hosts: all

  tasks:

  - name: define user1 and password
    ansible.builtin.user:
      name: "{{ custom_username }}"
      password: "{{ custom_password | password_hash('sha512') }}"
